config/routes.rb
Blog3::Application.routes.draw do

  devise_for :users

  get 'tags/:tag', to: 'posts#index', as: :tag

  get '/cloudtags', to: 'cloudtags#cloudtags'

  resources :posts do
    resources :comments
  end

  root :to => "posts#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  attr_accessible :name, :content

  validates :name,  :presence => true,
                    :length => { :within => 2..100 }

  validates :content,  :presence => true

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, :dependent => :destroy

  belongs_to :user

  attr_accessible :content, :title, :tag_list

  acts_as_taggable

  validates :title,   :presence => true,
                      :uniqueness => { :message => "already taken" },
                      :length => { :within => 2..255 }

  validates :content, :presence => true

  self.per_page = 5

  default_scope :order => 'posts.created_at DESC'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cloudtags_controller.rb
class CloudtagsController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params[:comment])
    @comment.post_id = @post.id

    if @comment.save
      redirect_to post_path(@post)
    else
      render "posts/show"
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index

    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(:page => params[:page])
    else
      @posts = Post.paginate(:page => params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(params[:post])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cloudtags_helper.rb
module CloudtagsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def join_tags(post)
    post.tags.map { |t| t.name }.join(", ")
  end

  def is_current_user_post(post)
    user_signed_in? and current_user.id == post.user_id
  end

  def post_user_name(post)
    User.find_by_id(post.user_id).email
  end

  def post_exceeded
    Post.count > Post.per_page
  end

end

app/views/cloudtags/cloudtags.html.erb
<div id="post_content">
  <div id="tag_cloud">
    <% if Post.any? %>
      <h1 class="title">Tag Cloud</h1>
      <br>
    <% end %>
    <p class="body">
    <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
    </p>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.content %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>

  <% if is_current_user_post(@post) %>
    <p>
      <%= link_to 'Destroy Comment', [comment.post, comment],
      :confirm => 'Are you sure?',
      :method => :delete,
      class: "button" %>
    </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

  <% if @comment && @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'b_logo_blue.png' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
      <%= image_tag "b_logo_blue.png"%>
      <% end %>
    </div>

    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "Tag Cloud", cloudtags_path %></li>
      <% if user_signed_in? %>
      <li><%= link_to 'New Post', new_post_path %></li>
      <% end %>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="https://github.com/adelinelim/myblog">Github</a></li>
      <li><a href="mailto:adelineyiing@gmail.com">Email</a></li>
    </ul>

  </div>

  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
        <p>All Posts</p>
      <% else %>
        <%= link_to "Back to All Posts", root_path %>
      <% end %>

      <% if user_signed_in? %>
        <div class="buttons">
          Logged in as <%= current_user.email %>
          <%#= link_to "New Post", new_post_path, class: "button" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "button" %>
        </div>
      <% else %>
        <div class="buttons">
          <%= link_to "Sign up", new_user_registration_path, class: "button" %>
          |
          <%= link_to "Log In", new_user_session_path, class: "button" %>
        </div>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, id: "notice") %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Editing post</h1>

  <%= render 'form' %>
  
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="body"><%= truncate post.content %></p>
    <p><b>Tags: </b><%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></p>
    <p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
    <% if is_current_user_post(post) %>
      <%= link_to "Edit Post", edit_post_path(post), class: "button" %>
      <%= link_to 'Destroy', post, class: "button", method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>
<% if post_exceeded %>
  <div class="post_wrapper">
    <%= will_paginate @posts %>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
<h1>New post</h1>

<%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div id="post_content">

<h1 class="title">
  <%= @post.title %>
</h1>

<p class="body">
  <%= simple_format @post.content %>
</p>

<p class="body">
  <b>Tags:</b>
  <%= join_tags(@post) %>
</p>

<p>Posted by: <%= post_user_name(@post) %></p>

<br />

<% if is_current_user_post(@post) %>
  <%= link_to 'Edit Post', edit_post_path(@post), class: "button" %>
<% end %>

<div id="comments">
  <h2><%= @post.comments.count %> Comments</h2>
  <%= render @post.comments %>

  <h3>Add a comment:</h3>
  <%= render "comments/form" %>
</div>

</div>